FROM quay.io/cogniteev/flume:1.6.0

ONBUILD RUN mkdir -p /var/src/extrajars
ONBUILD ADD interceptors /var/src/agent
ONBUILD RUN [ -f agent/interceptors/build.gradle ] && gradle build && \
    for jar in /var/src/agents/interceptors/build/lib/*.jar ; do \
        cp $jar /var/src/extrajars ; \
    done

ONBUILD ADD extrajars/* /var/src/agent/extrajars
