#!/bin/sh -e

cd /var/src/agent/extra-src
if [ -f build.gradle ] ; then
  touch .remove-me
  DOCKER_BUILD=true gradle build
  for jar in build/libs/*.jar ; do
    cp "$jar" /var/src/agent/extra-jars
  done
  for jar in libs/*.jar ; do
    cp "$jar" /var/src/agent/extra-jars
  done
  find . -type f -newer .remove-me -exec rm -rf \{\} \;
  rm -f .remove-me
  rm -rf ~/.m2
fi
