#!/bin/sh -e

cd /var/src/agent/extra-src
if [ -f build.gradle ] ; then
  touch .remove-me
  DOCKER_BUILD=true gradle build dist
  find dist -type f -name \*.jar \
    -exec cp \{\} /var/src/agent/extra-jars/ \;
  find . -type f -newer .remove-me -exec rm -rf \{\} \;
  rm -f .remove-me
  rm -rf ~/.m2
fi
