#!/bin/bash -e

FLUME_NG="$FLUME_INSTALL_DIR/bin/flume-ng"

# Perform environment variable expansion in all agent config file
find /var/src/agent/conf -type f -exec \
    perl -pe 's/\${([A-Z_]+)}/$ENV{$1}/g' -i \{\} \;

export AGENT_NAME="${AGENT_NAME:-agent}"
if [ $# = 0 ] ; then
    set -- "$FLUME_NG" agent                                \
    --conf "$AGENT_CONFIG_DIR"                              \
    --name "$AGENT_NAME"                                    \
    --conf-file "$AGENT_CONFIG_DIR/flume-conf.properties"   \
    "$@"
elif [ "${1:0:1}" = '-' ]; then
    set -- "$FLUME_NG" agent "$@"
fi

exec $@
